/* eslint no-param-reassign: 0 */
// We're allowed to disable this rule in this slice file as we're using Immu js library
import { createSlice } from '@reduxjs/toolkit';

import { retrieveBooks } from './books.actions';

const initialState = {
  books: [],
  isLoading: false,
};

export const counterSlice = createSlice({
  name: 'books',
  initialState,
  reducers: {
    addBook: (state, { payload }) => {
      state.books.push(payload);
    },
    removeBook: (state, { payload: removedBookId }) => {
      state.books = state.books.filter((book) => book.id !== removedBookId);
    },
  },
  extraReducers: {
    [retrieveBooks.pending]: (state) => {
      state.isLoading = true;
    },
    [retrieveBooks.fulfilled]: (state, { payload }) => {
      state.isLoading = false;
      state.books = [
        ...state.books,
        ...payload,
      ];
    },
    [retrieveBooks.rejected]: (state) => {
      state.isLoading = false;
    },
  },
});

// We can use actions generated by toolkit
// export const { addBook, removeBook } = counterSlice.actions;

export default counterSlice.reducer;
